### ISSUE TITLE
Manuscript Edit Suggestions 

### ISSUE THREAD

**Issue by zmousavi** [neurodata/MGC-paper#112]
line 19, 20: We here describe a procedure -> Here, we
line 35: , all of science -> , to all of science
**line 30: firs -> first**
line 43, 44:  for dependence-testing motivating -> for dependence-testing, motivating 
line 125, 126: and therefore faces > and therefore it faces
line 160: only close in x, not y -> only close in x, and not in y
line 179, 180: n=100, but dimensionality -> n=100, but with dimensionality
line 336: for each brain region g, we -> for each brain region, g, we 
line 357: map encoding which -> map encoding, which 
**line 359: succeeded -> succeed (match the tense with the rest of sentence)**

**Comment by jovo** [comment]
@cshen6 can you correct these?
@zmousavi thank you!

**Comment by cshen6** [comment]
ok, will correct. 

Once done I will push change and close this one
