### ISSUE TITLE
remaining

### ISSUE THREAD

**Issue by cshen6** [neurodata/MGC-paper#116]
- [x] go through \cs comments with jovo on Monday
- [x] go through appendix carefully
- [x] wait for 10000 MC replicates to finish and re-plot all power plots
- [x] write cover letter
- [x] post to arxiv Thursday
- [x] clean up the appendix once the main paper settles
- [x] cover letter need to have title and date changed later
- [x] have jovo re-generate all figures
- [ ] update arxiv?

**Comment by jovo** [comment]
once the 10,000 MC replicates are done, and we choose the title, i see no reason to not post to arxiv?

**Comment by cshen6** [comment]
yes! it should be done in one day.

Once we discuss a few more paper points thursday, we can probably post to arxiv that
day!

On Tue, Sep 13, 2016 at 1:10 PM, joshua vogelstein <notifications@github.com

**Comment by cshen6** [comment]
@jovo  
all mc replicates finished, so all simulation plots are re-drawn and updated on git/overleaf. 
much smoother with overall great power!
