### ISSUE TITLE
some triviality

### ISSUE THREAD

**Issue by cshen6** [neurodata/MGC-paper#117]
- [x] hhg overlay on mcorr in power plots.
- [x] slope graph with sample mgc
- [x] investigate false positives in Eklund

**Comment by cshen6** [comment]
@jovo 
- I actually made hhg overlap above all methods for clarity
- I realized we only have sample mgc for mcorr, so I cannot draw slopegraphs for sample mcorr / mantel / dcorr....since the sample and oracle have very similar advantages from type 6-19, and I am happy with live with the oracle version for the slopegraphs.
- For Eklund, they compared with parametric methods in their paper, which is why they have more false positives than expected. 
  To reflect this, in the abstract, I added "MGC does not suffer from .... by ""parametric methods"" "; and in real data section, I said "many standard parametric methods for fMRI analysis", and changed false discoveries to false positives, since we are not doing multiple testing here.

**Comment by jovo** [comment]
1) what do you think about at least looking at adding a 4th column for sample mgc vs. mcorr?
2) re:eklund, great!

**Comment by cshen6** [comment]
done!

you can check out the slopegraph on overleaf, and I slightly updated the
caption and its main text as well, as we probably want it there.

let me know if you want other improvement of the slopegraph.

On Mon, Sep 12, 2016 at 8:53 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
i would crop the sides so it fills with width of the screen.
other than that, i think ready to send back to ruth :)

**Comment by cshen6** [comment]
I slightly enlarged the figure. Will adjust it more once I send to Heller first
