### ISSUE TITLE
fig1 numbering

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#127]
i think it might make sense to number things:

A\emptyset
Ai
Aii
Aiii
Aiv

cuz right now, it says in the text Figure 10A, 10B, etc., which makes it look like fig 10, fig 11.

what do you think?

**Comment by cshen6** [comment]
currently, all appendix figure is A1, A2,...so forth.

So I think it is ok?

**Comment by jovo** [comment]
we have Fig A1 and 1A and it is confusing?

let's change the appendix ones to "supplementary" ones, eg Fig S1?

**Comment by cshen6** [comment]
ok, I changed A to S for figure, and all mention of appendix in tex to
supplementary
