### ISSUE TITLE
fig1 - which dots in the pairwise comparison plots are black?

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#131]
those corresponding to (k,l) from sampleMGC?

or those corresponding to any of the optimal (k,l)'s?

i think  it should be the latter, no?

**Comment by cshen6** [comment]
Both.

to be accurate, it corresponds to oracle MGC, or local MGC at k=l=4.

In this particular spiral example, the green dots in fig 2B actually
corresponds to k=l=4, so sample MGC equals oracle MGC for the observed data.
