### ISSUE TITLE
fig 1 of LLE & isomap

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#138]
look at them.
it is essentially _immediately_ obvious what they are doing, what is going on.
i love our figure 1, 
but it is not remotely like that.

**Comment by cshen6** [comment]
really? I thought you mean the opposite...

If you look at Isomap's figures (tenenbaum's paper), none of them are as
informative / useful as ours!
Arguably figure 3 is better, where they illustrate how Isomap unfolds the
swiss roll geometry.

Then in the LLE paper, figure 1 is about unfolding nonlinearity of swiss
roll, just like figure 3 of isomap; and figure 2 of LLE shows how their
method works; and remaining figures of LLE are about real data and not very
useful either.

So, in these two papers, essentially only figure 1 & 2 of LLE are great:
_they explain the actual steps of LLE for nonlinear embedding, and show how
LLE can be useful in unfolding nonlinearity by an example._

Our figures are far better and useful....In particular, our figure 1 shows:
_how MGC can be used to get p-value and optimal scale, how MGC is better
than existing methods, and two examples where MGC is useful in detecting
the linear/nonlinear correlations._

The only thing I think they did better, is how they colored the swiss roll
data, which makes it look fancier....We can do so for our first panel in
figure 1 too, if you wish...
