### ISSUE TITLE
no 'thres2' in MGCSampleStat function of Matlab code

### ISSUE THREAD

**Issue by shu-hai** [neurodata/MGC-paper#152]
Hi, I tried your new matlab code for MGC, but it gave me the error as follows:

Undefined function or variable 'thres2'.

Error in MGCSampleStat (line 55)
if mean(mean(R))>=thres2 % proceed only when the region
area is sufficiently large

Error in MGCPermutationTest (line 36)
    statMGC=MGCSampleStat(localCorr); % sample MGC for
    the observed data

**Comment by cshen6** [comment]
thanks! it is fixed now.
