### ISSUE TITLE
MGC

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#160]
you do this thing some times:

"denote the optimal local correlation as the multiscale generalized correlation"

MGC is the algorithm? or the test statistic?  
let's not overload it, let's choose one, and always mean that.
i thought it meant the algorithm.
do you want it to mean the test statistic instead?

i think the test statistic is called the "MGC statistic"?

**Comment by jovo** [comment]
here's another example:

"we always define the optimal local correlation (i.e., Oracle \Mgc) as the local correlations that maximize power"


i changed to "Oracle \Mgc~selects the scale that maximizes power."

**Comment by cshen6** [comment]
yes indeed. I changed them to \Mgc statistic, and \Mgc selects the optimal correlation accordingly.
