### ISSUE TITLE
fig consistency

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#164]
in our multiscale power maps, we have 3 different axis labels:

- in fig 1, we write " X scales"
- in fig 3, we write "# of X Neighbors"
- in fig 4, we write "X Neighbors"

let's pick one and use it for all 3?

i vote we try:

- "# of X Neighbors", but if it doesn't fit, we revert to:
- "X Neighbors (#)", then
- "# X Neighbors", then,
- "X Neighors"

what do you think?

**Comment by cshen6** [comment]
"# X Neighbors" looks good enough.

Changed all figures accordingly
