### ISSUE TITLE
update documentation or tutorial to avoid the mistake that shangsi made

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#170]

**Comment by jovo** [comment]
i don't recall what it is anymore, so i don't know how to do this, 
and @cshen6 seemed to be uninterested in doing it.
so i'm closing it.
@cshen6 re-open if you know how to fix this issue.

**Comment by cshen6** [comment]
I still remember what it is; and related to cep's post-model question, i.e., one should use sample mgc stat, rather than individual local corr for testing on real data.

I added comments in the main permutation test; hopefully it will avoid potential mis-use.
