### ISSUE TITLE
in multiscale heatmaps

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#176]
why are you only plotting to 'n-1', instead of to 'n'?

**Comment by jovo** [comment]
there is a merge conflict in 'plot_simulation_heatmaps'
but i don't understand why you are not showing the last row/col of the heatmaps
i modified it in plot_panel5 to show up to n,
but i'm confused why you did that in the first place

**Comment by cshen6** [comment]
fixing the heatmap screw.

Also I modified panel 5 back. 

Because we are always showing scales from 2 to n, instead of 1 to n. (scale 1 will have zero correlation and power). 

In code it is 1 to n-1, rather than 2 to n.

**Comment by cshen6** [comment]
all fixed and synced.

**Comment by jovo** [comment]
i see.
