### ISSUE TITLE
% if p-value equals 0...

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#180]
% if p-value equals 0, enlarge it to 1/rep, since the identity permutation is always
% one such permutation.
if min(min(pLocalCorr(2:end,2:end)))==0
    pLocalCorr=pLocalCorr+1/rep;
end

what is this? it seems wrong.
in permutation test, if all your samples are more null like than the observed, then p < 1/n.
this is your kludge for reporting p < 1/n?

on the other hand, if you actually got 1 permutation that looked like the alternative, in which case, p = 1/n.

in your code, you report the same thing, which is not technicallly correct, your p-value is biased.

not really a big deal perhaps, it should be p = 1/(n+eps_n), where eps_n --> 0 as n --> infty.
perhaps your rate of convergence is fast.

**Comment by cshen6** [comment]
ok, keep the same output but changed the comment...
