### ISSUE TITLE
adaptive (k,l)

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#200]
i got a question when i gave a talk last week about letting (k,l) change for each sample.
[Zhang12a.pdf](https://github.com/neurodata/MGC/files/709053/Zhang12a.pdf)

here is a paper that tries to deal with that for manifold learning (in particular, LTSA, which is the best manifold learning imho).

not sure there is much for us to take from this, but seems definitely worth reading...

**Comment by cshen6** [comment]
I don't think there is anything new to get from this one. Details replied in email.
