### ISSUE TITLE
put gray dot in each other panels

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#202]
this includes the panels in fig 4, 
and in fig E2 (the power plot)

**Comment by cshen6** [comment]
ok it is added across board

**Comment by jovo** [comment]
@cshen6 sorry i wasn't clear, i meant *only* add to fig 4 and E2, 
we do *not* want it in Fig 3 or E6.

**Comment by cshen6** [comment]
ok no problem, switched back the heatmaps to no gray dots.
