### ISSUE TITLE
put the good version of this image in github

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#216]
http://docs.neurodata.io/MGC/#10

**Comment by cshen6** [comment]
it is on git (the dotted version used in paper)

https://github.com/neurodata/MGC/blob/master/Figures/FigHDPowerMGCM.pdf

Previously the png version is not updated; so I removed png pictures for
now.


Or you would like the pic to be uploaded to other repo?
Or would like the png version updated instead?

**Comment by jovo** [comment]
I use the png's in the website, so yes, please keep the pngs updated.
Thanks.

**Comment by cshen6** [comment]
updated all png versions; 
and default the figure output to png instead of pdf.
(As pdf figure generation may get notation \pi into : in adobe reader; but png is always fine)
