### ISSUE TITLE
remaining theoretical quesitons

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#31]
1. [x] is the p-value we obtain using the new procedure unbiased? if so, how. if not, we can prove it?
2. [x] does our procedure for choosing (k,l) give us a good answer? i guess we'd want (k_,l_) from our procedure to be close to the highest power from  many simulations for a fixed n? 

not obvious we need to prove either of these things for the paper, but we definitely need to think about ;)

**Comment by jovo** [comment]
for 2 above, make the powerscale maps without using the true density (ie, using our smoothed bootstrap procedure)

**Comment by cshen6** [comment]
we are valid now
