### ISSUE TITLE
FlashR?

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#33]
@icoming what would it take to make https://github.com/jovo/RankdCorr/blob/master/Code/R/localGraphCorr.R work in FlashR?

note: currently, we compute all pairwise distances using the energy package, 
and then we convert all of them to ranks, 
and then some stuff.

when n is large, we would use an approximation: only compute the k-neighbors (for some specified k).

what do you think?

also note: the code shows how to 'double center' using array operations.

**Comment by zheng-da** [comment]
The code isn't very array-oriented and isn't very scalable.
It uses double for loops to access matrix elements and uses n x n matrices.
I think the code needs to be rewritten.

**Comment by jovo** [comment]
ok, once we submit the paper, we'll work on re-writing the code to FlashR spec.
