### ISSUE TITLE
make fig0 3d

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#37]

**Comment by cshen6** [comment]
not all simulations can be made into 3d: say in case of joint normal, [x,y]
is either dimension 2 or 4 or 6, etc.

This is true for all simulations where d_{x}=d_{y}.

What do you think? Or I can try to draw x versus y_{1}.

**Comment by jovo** [comment]
x vs. y1 is great!

On Thu, Feb 4, 2016 at 7:07 AM, cshen6 notifications@github.com wrote:

> not all simulations can be made into 3d: say in case of joint normal, [x,y]
> is either dimension 2 or 4 or 6, etc.
> 
> This is true for all simulations where d_{x}=d_{y}.
> 
> What do you think? Or I can try to draw x versus y_{1}.
> 
> On Wed, Feb 3, 2016 at 1:32 PM, joshua vogelstein <
> notifications@github.com>
> wrote:
> 
> > Assigned #37 https://github.com/jovo/RankdCorr/issues/37 to @cshen6
> > https://github.com/cshen6.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jovo/RankdCorr/issues/37#event-537989045.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/RankdCorr/issues/37#issuecomment-179792296.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by cshen6** [comment]
I just checked the 3D plot of fig 0, but think it might be better to use
the 2D version:

All 3D dependencies match the description of each type (yeah!),
and is the natural extension of the current 2D version;

But we need to manually adjust the axis so the 3D figure illustrates the
shape & geometry,
and the geometry is better shown and usually more clear under 2D.

Another tech difficulty is that I cannot put 20 3D figures in a same panel
in Matlab...It simply gets stuck for doing so. But we can output each
figure and paste them together later if necessary.

You can check the 3D figure for each type, by the following command:

type=1; % change type from 1 to 20
[x, y]=CorrSampleGenerator(type,1000,2,1,0);
plot3(x(:,1),x(:,2),y(:,1),'r.');

Let me know what you think?
(And did you see the attachment in my other email?)

**Comment by jovo** [comment]
i agree, 2D are better.
i'm glad we looked at the 3D figures though :)

i didn't quite follow the attachments in the other email.

let's replace the current first real data application with the MIGRAINE vs
CCI application?
once you add the figure, i can add the text.
let's make it second, after the shape vs disease application.

thanks!

On Fri, Feb 12, 2016 at 8:52 PM, cshen6 notifications@github.com wrote:

> I just checked the 3D plot of fig 0, but think it might be better to use
> the 2D version:
> 
> All 3D dependencies match the description of each type (yeah!),
> and is the natural extension of the current 2D version;
> 
> But we need to manually adjust the axis so the 3D figure illustrates the
> shape & geometry,
> and the geometry is better shown and usually more clear under 2D.
> 
> Another tech difficulty is that I cannot put 20 3D figures in a same panel
> in Matlab...It simply gets stuck for doing so. But we can output each
> figure and paste them together later if necessary.
> 
> You can check the 3D figure for each type, by the following command:
> 
> type=1; % change type from 1 to 20
> [x, y]=CorrSampleGenerator(type,1000,2,1,0);
> plot3(x(:,1),x(:,2),y(:,1),'r.');
> 
> Let me know what you think?
> (And did you see the attachment in my other email?)
> 
> On Thu, Feb 4, 2016 at 7:27 AM, joshua vogelstein <
> notifications@github.com>
> wrote:
> 
> > x vs. y1 is great!
> > 
> > On Thu, Feb 4, 2016 at 7:07 AM, cshen6 notifications@github.com wrote:
> > 
> > > not all simulations can be made into 3d: say in case of joint normal,
> > > [x,y]
> > > is either dimension 2 or 4 or 6, etc.
> > > 
> > > This is true for all simulations where d_{x}=d_{y}.
> > > 
> > > What do you think? Or I can try to draw x versus y_{1}.
> > > 
> > > On Wed, Feb 3, 2016 at 1:32 PM, joshua vogelstein <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > Assigned #37 https://github.com/jovo/RankdCorr/issues/37 to
> > > > @cshen6
> > > > https://github.com/cshen6.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/jovo/RankdCorr/issues/37#event-537989045.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/jovo/RankdCorr/issues/37#issuecomment-179792296.
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > neurodata.io
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jovo/RankdCorr/issues/37#issuecomment-179802005.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/RankdCorr/issues/37#issuecomment-183559335.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by cshen6** [comment]
in migraine vs cci, local and global are both significant; that is ok?

if so, we will have
1. migraine vs cci, where both are significant;
2. shape vs disease, where local is significant;
3. CORR data vs random signal, where neither is significant,

right?

**Comment by cshen6** [comment]
nah, migraine vs cci should be the second :-)

about the attachment in the other email, let us chat a bit on Skype today
or tomorrow when you are free?

**Comment by jovo** [comment]
1-3 sound great

ok, maybe noon today?

**Comment by cshen6** [comment]
sounds great; talk to you later.
