### ISSUE TITLE
performance profile AUCs are wrong or confusing

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#40]

**Comment by cshen6** [comment]
Looks correct to me. Which part is confusing? the threshold?

**Comment by jovo** [comment]
say, in fig (A), HGG has AUC much LOWER than say global dcorr,
but it is doing much better.

On Wed, Mar 2, 2016 at 8:44 AM, cshen6 notifications@github.com wrote:

> Looks correct to me. Which part is confusing? the threshold?
> 
> On Wed, Mar 2, 2016 at 8:21 AM, joshua vogelstein <
> notifications@github.com>
> wrote:
> 
> > Assigned #40 https://github.com/jovo/RankdCorr/issues/40 to @cshen6
> > https://github.com/cshen6.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jovo/RankdCorr/issues/40#event-574641536.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/RankdCorr/issues/40#issuecomment-191243286.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by cshen6** [comment]
From what I see:

on page 12 Fig 3 (a), HHG (the black line) is higher than all global
methods (except x<0.15), but lower than local methods. The same holds for
(b)/(c)/(d).

Are we looking at different versions?

**Comment by jovo** [comment]
right, but the AUC for HHG is NOT higher than the global:

HHG: 0.549
dcorr: 0.934

On Wed, Mar 2, 2016 at 10:18 AM, cshen6 notifications@github.com wrote:

> From what I see:
> 
> on page 12 Fig 3 (a), HHG (the black line) is higher than all global
> methods (except x<0.15), but lower than local methods. The same holds for
> (b)/(c)/(d).
> 
> Are we looking at different versions?
> 
> On Wed, Mar 2, 2016 at 9:03 AM, joshua vogelstein <
> notifications@github.com>
> wrote:
> 
> > say, in fig (A), HGG has AUC much LOWER than say global dcorr,
> > but it is doing much better.
> > 
> > On Wed, Mar 2, 2016 at 8:44 AM, cshen6 notifications@github.com wrote:
> > 
> > > Looks correct to me. Which part is confusing? the threshold?
> > > 
> > > On Wed, Mar 2, 2016 at 8:21 AM, joshua vogelstein <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > Assigned #40 https://github.com/jovo/RankdCorr/issues/40 to
> > > > @cshen6
> > > > https://github.com/cshen6.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/jovo/RankdCorr/issues/40#event-574641536.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/jovo/RankdCorr/issues/40#issuecomment-191243286.
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > neurodata.io
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jovo/RankdCorr/issues/40#issuecomment-191248997.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/RankdCorr/issues/40#issuecomment-191283445.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by cshen6** [comment]
Indeed!!

Corrected on github now.

On Wed, Mar 2, 2016 at 11:37 AM, joshua vogelstein <notifications@github.com

> wrote:
> 
> right, but the AUC for HHG is NOT higher than the global:
> 
> HHG: 0.549
> dcorr: 0.934
>
