### ISSUE TITLE
why does HHG thump in diamond?

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#41]

**Comment by cshen6** [comment]
since there is no theoretical guarantee that MGC will beat HHG, it is
possible that HHG may win under some dependencies.

we have went through this before; and I think HHG superiority in 1 out of
20 is fine.

we can discard it if necessary; and there are not much argument we can
say under the diamond case.

**Comment by jovo** [comment]
i meant the intuition?
i think we can learn something from the fact that it is thumping.
what property does it have that we lack that might explain it?

eg, if we were rotationally invariant, would we thump it?

On Wed, Mar 2, 2016 at 8:46 AM, cshen6 notifications@github.com wrote:

> since there is no theoretical guarantee that MGC will beat HHG, it is
> possible that HHG may win under some dependencies.
> 
> we have went through this before; and I think HHG superiority in 1 out of
> 20 is fine.
> 
> we can discard it if necessary; and there are not much argument we can
> say under the diamond case.
> 
> On Wed, Mar 2, 2016 at 8:23 AM, joshua vogelstein <
> notifications@github.com>
> wrote:
> 
> > Assigned #41 https://github.com/jovo/RankdCorr/issues/41 to @cshen6
> > https://github.com/cshen6.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jovo/RankdCorr/issues/41#event-574643692.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/RankdCorr/issues/41#issuecomment-191244253.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by cshen6** [comment]
I thought about it, but fail to reach a good intuition here...

Since HHG uses Pearson's chi-square table in a complex way, it is very hard
to justify why HHG can be better or worse in general.
The authors do not theoretically justify its advantage over dcorr either,
albeit showing their numerical advantage in the original paper.

For your reference,
I checked the test statistics for type 15 diamond, see attached plot:
tmpHHG15.png shows the HHG statistic (its kernel density approximation
after 1000 replicates) under the null and alternative.
tmpMGC15.png shows the MGC{mcorr} density under the null and alternative.

Similarly, I check the test statistic density for type 14 square, see
attached tmpHHG14 & tmpMGC14.

Note that MGC has a similar power as HHG in type 14, but inferior in type
15, which can be observed from the plots.

Other than that, I cannot find anything else that is un-usual.....

**Comment by cshen6** [comment]
ok, let's put a couple sentences in the discussion about
http://projecteuclid.org/euclid.bj/1411134461

The affinely invariant distance correlation

and say how that might affect performance in setting 15?

On Fri, Mar 4, 2016 at 3:04 PM, Cencheng Shen cshen@temple.edu wrote:

> I thought about it, but fail to reach a good intuition here...
> 
> Since HHG uses Pearson's chi-square table in a complex way, it is very
> hard to justify why HHG can be better or worse in general.
> The authors do not theoretically justify its advantage over dcorr either,
> albeit showing their numerical advantage in the original paper.
> 
> For your reference,
> I checked the test statistics for type 15 diamond, see attached plot:
> tmpHHG15.png shows the HHG statistic (its kernel density approximation
> after 1000 replicates) under the null and alternative.
> tmpMGC15.png shows the MGC{mcorr} density under the null and alternative.
> 
> Similarly, I check the test statistic density for type 14 square, see
> attached tmpHHG14 & tmpMGC14.
> 
> Note that MGC has a similar power as HHG in type 14, but inferior in type
> 15, which can be observed from the plots.
> 
> Other than that, I cannot find anything else that is un-usual.....
> 
> On Wed, Mar 2, 2016 at 9:06 AM, joshua vogelstein <
> notifications@github.com> wrote:
> 
> > i meant the intuition?
> > i think we can learn something from the fact that it is thumping.
> > what property does it have that we lack that might explain it?
> > 
> > eg, if we were rotationally invariant, would we thump it?
> > 
> > On Wed, Mar 2, 2016 at 8:46 AM, cshen6 notifications@github.com wrote:
> > 
> > > since there is no theoretical guarantee that MGC will beat HHG, it is
> > > possible that HHG may win under some dependencies.
> > > 
> > > we have went through this before; and I think HHG superiority in 1 out
> > > of
> > > 20 is fine.
> > > 
> > > we can discard it if necessary; and there are not much argument we can
> > > say under the diamond case.
> > > 
> > > On Wed, Mar 2, 2016 at 8:23 AM, joshua vogelstein <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > Assigned #41 https://github.com/jovo/RankdCorr/issues/41 to @cshen6
> > > > https://github.com/cshen6.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/jovo/RankdCorr/issues/41#event-574643692.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/jovo/RankdCorr/issues/41#issuecomment-191244253.
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > neurodata.io
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jovo/RankdCorr/issues/41#issuecomment-191249587.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by cshen6** [comment]
I quickly checked out the paper; but the affinely transformed dcorr is not
useful for improving the power in setting 15.

In particular, I quickly tested type 14 diamond and type 15 square; MGC by
affinely transformed mcorr/dcorr have similar powers as MGC by mcorr/dcorr,
which are lower than HHG for 15.

Furthermore, affine transformed dcorr is asymptotically same as original
dcorr.

Other than the above trial, I cannot see how we can use that paper to offer
more discussions?

**Comment by cshen6** [comment]
right, but they all have asymptotic power = 1 in this setting.
the question is of convergence rate.
so, you mean similar power vs. sample size curves?

On Mon, Mar 7, 2016 at 8:18 PM, Cencheng Shen cshen@temple.edu wrote:

> I quickly checked out the paper; but the affinely transformed dcorr is not
> useful for improving the power in setting 15.
> 
> In particular, I quickly tested type 14 diamond and type 15 square; MGC by
> affinely transformed mcorr/dcorr have similar powers as MGC by mcorr/dcorr,
> which are lower than HHG for 15.
> 
> Furthermore, affine transformed dcorr is asymptotically same as original
> dcorr.
> 
> Other than the above trial, I cannot see how we can use that paper to
> offer more discussions?
> 
> On Mon, Mar 7, 2016 at 7:27 PM, joshua vogelstein jovo@jhu.edu wrote:
> 
> > ok, let's put a couple sentences in the discussion about
> > http://projecteuclid.org/euclid.bj/1411134461
> > 
> > The affinely invariant distance correlation
> > 
> > and say how that might affect performance in setting 15?
> > 
> > On Fri, Mar 4, 2016 at 3:04 PM, Cencheng Shen cshen@temple.edu wrote:
> > 
> > > I thought about it, but fail to reach a good intuition here...
> > > 
> > > Since HHG uses Pearson's chi-square table in a complex way, it is very
> > > hard to justify why HHG can be better or worse in general.
> > > The authors do not theoretically justify its advantage over dcorr
> > > either, albeit showing their numerical advantage in the original paper.
> > > 
> > > For your reference,
> > > I checked the test statistics for type 15 diamond, see attached plot:
> > > tmpHHG15.png shows the HHG statistic (its kernel density approximation
> > > after 1000 replicates) under the null and alternative.
> > > tmpMGC15.png shows the MGC{mcorr} density under the null and alternative.
> > > 
> > > Similarly, I check the test statistic density for type 14 square, see
> > > attached tmpHHG14 & tmpMGC14.
> > > 
> > > Note that MGC has a similar power as HHG in type 14, but inferior in
> > > type 15, which can be observed from the plots.
> > > 
> > > Other than that, I cannot find anything else that is un-usual.....
> > > 
> > > On Wed, Mar 2, 2016 at 9:06 AM, joshua vogelstein <
> > > notifications@github.com> wrote:
> > > 
> > > > i meant the intuition?
> > > > i think we can learn something from the fact that it is thumping.
> > > > what property does it have that we lack that might explain it?
> > > > 
> > > > eg, if we were rotationally invariant, would we thump it?
> > > > 
> > > > On Wed, Mar 2, 2016 at 8:46 AM, cshen6 notifications@github.com
> > > > wrote:
> > > > 
> > > > > since there is no theoretical guarantee that MGC will beat HHG, it is
> > > > > possible that HHG may win under some dependencies.
> > > > > 
> > > > > we have went through this before; and I think HHG superiority in 1
> > > > > out of
> > > > > 20 is fine.
> > > > > 
> > > > > we can discard it if necessary; and there are not much argument we can
> > > > > say under the diamond case.
> > > > > 
> > > > > On Wed, Mar 2, 2016 at 8:23 AM, joshua vogelstein <
> > > > > notifications@github.com>
> > > > > wrote:
> > > > > 
> > > > > > Assigned #41 https://github.com/jovo/RankdCorr/issues/41 to
> > > > > > @cshen6
> > > > > > https://github.com/cshen6.
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > https://github.com/jovo/RankdCorr/issues/41#event-574643692.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/jovo/RankdCorr/issues/41#issuecomment-191244253.
> > > > 
> > > > ## 
> > > > 
> > > > the glass is all full: half water, half air.
> > > > neurodata.io
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/jovo/RankdCorr/issues/41#issuecomment-191249587.
> > 
> > ## 
> > 
> > the glass is all full:  half water, half air.
> > neurodata.io

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by cshen6** [comment]
yes that is what I mean; which is why I think affine transformed dcorr is
not more useful than dcorr.

Say at n=100, d=1, type 15, both dcorr and affine transformed dcorr have
power 0.6 while HHG has power 0.98.
