### ISSUE TITLE
figure edits for sending to gabor

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#45]
- all fonts in figs should be approximately the same size as the fonts in the main text.
-  fig 1: 
  - [x] remove numbers on X & Y axes
  - [x] remove scale bars
  - [x] can't read titles, so, make fonts bigger, might need to use A, Atilde, etc. to fit it in.
- fig 2:
  - [x] change title to: "Testing Power for 20 Simulated 1-Dimensional Settings" 
- fig 3:
  - [x] title a: "Performance Profiles for 1-Dimensional Settings"
  - [x] b: you might need to use "AUC" when the font is bigger
  - [x] c: "Performance Profiles for High-Dimensional Settings"
  - [x] c caption: "at the last dimension of "  last=largest? please clarify
  - [x] d: might need to use AUC
- fig 4: 
  - [x] change title to: "Testing Power for 20 Simulated High-Dimensional Settings with Fixed Sample Size"
- fig 5:
  - [x] "Testing Power for All Local Tests of mcorr in High-Dimensional Settings"
  - [x] change X & Y labels to "Number of Neighbors for X" and same for Y.  same applies to other heatmaps
  - [x] i don't understand from the caption how you chose which dimension to use. 
-  [x] fig 6: needs a scalebar
- table 1: 
  - [x] font sizes are too small in the table, make bold the smallest result in each row.
  - [x] caption should be a proper sentence, and just like the figure captions, eg, explain what is goign on more, what is the take home message.
- [x] fig 7b: keep the same color scheme as the previous figures.  fonts on x-axis might have to stay small here. 
- [x] the figures in the appendix the numbering starts over which is confusing.  they should continue, or be numbered A1, A2, etc.
- [x] fig A1: make same changes as above
- [x] fig A3: 
  - [x] make lines thicker. also, why is TRUE MGC the same color as Global MCORR? it should be the same color as ESTIMATED MCORR, right? keep the same color scheme throughout. 
    - [x] fix titles

**Comment by jovo** [comment]
@cshen6 please check off the ones you did, so we can see if anything is left.

**Comment by cshen6** [comment]
@jovo 
I check again and all are done, and updated a few descriptions on github.

You may want to check fig 5 title, the dimension explanation in the caption, figure 6 caption, figure 7b font size, to see if you are satisfied with them.

Note that A3 are done differently from the checkbox content, but we discussed about it already.

**Comment by jovo** [comment]
great, then you can close this issue.

in the high-dimensional simulations, the multiplicative noise setting seems
to easy,
in that all the local versions, and HHG, always do perfect?

can we make that harder, so as n increases, they stop being perfect?

On Friday, June 3, 2016, cshen6 notifications@github.com wrote:

> @jovo https://github.com/jovo
> I check again and all are done, and updated a few descriptions on github.
> 
> You may want to check fig 5 title, the dimension explanation in the
> caption, figure 6 caption, to see if you are satisfied with them.
> 
> Note that A3 are done differently from the checkbox content, but we
> discussed about it already.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/RankdCorr/issues/45#issuecomment-223451255, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcqvfHjsoCwmUJpm4-fNMp8gxn_48ks5qH2VxgaJpZM4IY0Ed
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
@jovo 

Yes there is a typo for type 18 in hd, and I fixed it in tex on git.

The relevant figure may take a day or so to update, for simulation to finish all MC replicates.
