### ISSUE TITLE
organize matlab code folder like the LOL/code folder

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#46]

**Comment by cshen6** [comment]
the folder structure for code & data are organized like the LOL one.

take a look and let me know if it looks satisfactory?

**Comment by jovo** [comment]
is great, but no spaces in folder/file names please!

**Comment by cshen6** [comment]
you mean the "R version" folder I guess.

Will replace space with "_" in next push...

On Wed, Jun 8, 2016 at 12:41 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
or just "R"

**Comment by cshen6** [comment]
Updated again. I think this one can be close now.
