### ISSUE TITLE
shouldn't we compute power for the outlier examples using the other approaches?

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#49]

**Comment by cshen6** [comment]
For local vs global, you can see from the heatmaps that local is always
better than global.
That holds for all global corr under the outlier model.

The only other benchmark is HHG, which performs same as local corr under
the outlier case.

We can mention HHG performance in the main paper, or just leave it as it
is:
because a better testing power is not the main theme for that section, and
HHG doesn't shed lights into the outlier structure while our local corr
does :-)

**Comment by jovo** [comment]
agreed, though we should mention HHG power in the text for all 3 settings
anyway.

On Tuesday, June 7, 2016, cshen6 notifications@github.com wrote:

> For local vs global, you can see from the heatmaps that local is always
> better than global.
> That holds for all global corr under the outlier model.
> 
> The only other benchmark is HHG, which performs same as local corr under
> the outlier case.
> 
> We can mention HHG performance in the main paper, or just leave it as it
> is:
> because a better testing power is not the main theme for that section, and
> HHG doesn't shed lights into the outlier structure while our local corr
> does :-)
> 
> On Mon, Jun 6, 2016 at 3:15 PM, joshua vogelstein <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > Assigned #49 https://github.com/jovo/RankdCorr/issues/49 to @cshen6
> > https://github.com/cshen6.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/jovo/RankdCorr/issues/49#event-683323224, or mute
> > the thread
> > <
> > https://github.com/notifications/unsubscribe/ALX0y3YE5XrYi8uph9q7ZjemNYvCw1_wks5qJHHUgaJpZM4IvOFn
> > 
> > .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/RankdCorr/issues/49#issuecomment-224131680, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcgkKgznW0tfaNKy086BH-jLyWpbbks5qJL_5gaJpZM4IvOFn
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
"Note that although global correlation does not perform well, HHG performs
as well as MGC under the outlier model; but our local correlations provide
very useful information regarding the intrinsic structure of the
dependency, while HHG does not."

Adding above to tex should be sufficient?

**Comment by jovo** [comment]
yup, is that really true?
for all 3 different fractions of outliers?

On Tue, Jun 7, 2016 at 1:30 PM, cshen6 notifications@github.com wrote:

> "Note that although global correlation does not perform well, HHG performs
> as well as MGC under the outlier model; but our local correlations provide
> very useful information regarding the intrinsic structure of the
> dependency, while HHG does not."
> 
> Adding above to tex should be sufficient?
> 
> On Tue, Jun 7, 2016 at 2:07 AM, joshua vogelstein <
> notifications@github.com>
> wrote:
> 
> > agreed, though we should mention HHG power in the text for all 3 settings
> > anyway.
> > 
> > On Tuesday, June 7, 2016, cshen6 notifications@github.com wrote:
> > 
> > > For local vs global, you can see from the heatmaps that local is always
> > > better than global.
> > > That holds for all global corr under the outlier model.
> > > 
> > > The only other benchmark is HHG, which performs same as local corr
> > > under
> > > the outlier case.
> > > 
> > > We can mention HHG performance in the main paper, or just leave it as
> > > it
> > > is:
> > > because a better testing power is not the main theme for that section,
> > > and
> > > HHG doesn't shed lights into the outlier structure while our local corr
> > > does :-)
> > > 
> > > On Mon, Jun 6, 2016 at 3:15 PM, joshua vogelstein <
> > > notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > wrote:
> > > 
> > > > Assigned #49 https://github.com/jovo/RankdCorr/issues/49 to
> > > > @cshen6
> > > > https://github.com/cshen6.
> > > > 
> > > > —
> > > > You are receiving this because you were mentioned.
> > > > Reply to this email directly, view it on GitHub
> > > > https://github.com/jovo/RankdCorr/issues/49#event-683323224, or
> > > > mute
> > > > the thread
> > > > <
> > 
> > https://github.com/notifications/unsubscribe/ALX0y3YE5XrYi8uph9q7ZjemNYvCw1_wks5qJHHUgaJpZM4IvOFn
> > 
> > > > .
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/jovo/RankdCorr/issues/49#issuecomment-224131680,
> > > or mute
> > > the thread
> > > <
> > 
> > https://github.com/notifications/unsubscribe/AACjcgkKgznW0tfaNKy086BH-jLyWpbbks5qJL_5gaJpZM4IvOFn
> > 
> > > .
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > neurodata.io, jovo calendar
> > <
> > 
> > https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
> > 
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/jovo/RankdCorr/issues/49#issuecomment-224188011,
> > or mute
> > the thread
> > <
> > https://github.com/notifications/unsubscribe/ALX0y0SDXIocMuKTaA43fUJuy33sXAQHks5qJQqSgaJpZM4IvOFn
> > 
> > .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/RankdCorr/issues/49#issuecomment-224253526, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcvWXITwKUeMwNmFut1ke2GkkSX1Rks5qJVZhgaJpZM4IvOFn
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
I remembered it is true, but let me double check on this.

**Comment by jovo** [comment]
yes please report numbers in this issue.
we can then make that statement if it is true.

On Tue, Jun 7, 2016 at 1:38 PM, cshen6 notifications@github.com wrote:

> I remembered it is true, but let me double check on this.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/RankdCorr/issues/49#issuecomment-224255107, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcnIA6ZirhZQIHNZ8Df54etfY8Ciaks5qJVhNgaJpZM4IvOFn
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
for w=0.5 & 0.7, all MGC and HHG are of power 1.

for w=0.3, HHG only has power 0.8 though.

So our method is better as outlier increases. 

I shall add below?
"Note that both MGC and HHG have power 1 for w=0.5 and 0.7. But as the percentage of outliers increases, MGC becomes better, and HHG has a power of 0.8 while MGC still maintains power 1 at w=0.3. Moreover, our local correlations provide very useful information regarding the intrinsic structure of the dependency, while HHG does not."

**Comment by jovo** [comment]
power is too high :)

maybe decrease the correlation,
eg, Sigma_1 = [1 k; k 1], where k < 1.

and we'll do better in all cases?

On Tuesday, June 7, 2016, cshen6 notifications@github.com wrote:

> for w=0.5 & 0.7, all MGC and HHG are of power 1.
> 
> for w=0.3, HHG only has power 0.8 though.
> 
> So our method is better as outlier increases.
> 
> I shall add below?
> "Note that both MGC and HHG have power 1 for w=0.5 and 0.7. But as the
> percentage of outliers increases, MGC becomes better, and HHG has a power
> of 0.8 while MGC still maintains power 1 at w=0.3. Moreover, our local
> correlations provide very useful information regarding the intrinsic
> structure of the dependency, while HHG does not."
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/RankdCorr/issues/49#issuecomment-224409554, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcunt0liKfeRg-8Da0XojrLXCd6YRks5qJdk1gaJpZM4IvOFn
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
I set k=0.9, so visually the dependency part is still almost linear.

MGC is always power 1 for w=0.3-0.7.
HHG has power 1 at w=0.7;
0.76 at w=0.5;
then 0 at w=0.3.

If we further reduce k, we can also get HHG to be worse than MGC at w=0.7;
but then the dependency part looks more like the independent part visually.

So I feel setting k=0.9 here should be sufficient for our purpose?

See attached for the outlier model visualization & powers.

**Comment by cshen6** [comment]
sounds great.  for labels:

row 1: example dataset
row 2: Multiscale Power Map

label columns:

col 1: 30% outliers
col 2: 50% outliers
etc...

On Wed, Jun 8, 2016 at 5:03 AM, Cencheng Shen cshen6@jhu.edu wrote:

> I set k=0.9, so visually the dependency part is still almost linear.
> 
> MGC is always power 1 for w=0.3-0.7.
> HHG has power 1 at w=0.7;
> 0.76 at w=0.5;
> then 0 at w=0.3.
> 
> If we further reduce k, we can also get HHG to be worse than MGC at w=0.7;
> but then the dependency part looks more like the independent part visually.
> 
> So I feel setting k=0.9 here should be sufficient for our purpose?
> 
> See attached for the outlier model visualization & powers.
> 
> On Tue, Jun 7, 2016 at 4:57 PM, joshua vogelstein <
> notifications@github.com> wrote:
> 
> > power is too high :)
> > 
> > maybe decrease the correlation,
> > eg, Sigma_1 = [1 k; k 1], where k < 1.
> > 
> > and we'll do better in all cases?
> > 
> > On Tuesday, June 7, 2016, cshen6 notifications@github.com wrote:
> > 
> > > for w=0.5 & 0.7, all MGC and HHG are of power 1.
> > > 
> > > for w=0.3, HHG only has power 0.8 though.
> > > 
> > > So our method is better as outlier increases.
> > > 
> > > I shall add below?
> > > "Note that both MGC and HHG have power 1 for w=0.5 and 0.7. But as the
> > > percentage of outliers increases, MGC becomes better, and HHG has a
> > > power
> > > of 0.8 while MGC still maintains power 1 at w=0.3. Moreover, our local
> > > correlations provide very useful information regarding the intrinsic
> > > structure of the dependency, while HHG does not."
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/jovo/RankdCorr/issues/49#issuecomment-224409554,
> > > or mute
> > > the thread
> > > <
> > > https://github.com/notifications/unsubscribe/AACjcunt0liKfeRg-8Da0XojrLXCd6YRks5qJdk1gaJpZM4IvOFn
> > > 
> > > .
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > neurodata.io, jovo calendar
> > <
> > https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
> > 
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/jovo/RankdCorr/issues/49#issuecomment-224412051, or mute
> > the thread
> > https://github.com/notifications/unsubscribe/ALX0y1se6HhbEBCpmvRXCbCGsDVx9RiSks5qJdtIgaJpZM4IvOFn
> > .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
done in the update just now.
