### ISSUE TITLE
new minor issues arising

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#50]
### @cshen6
- in fig1
  -  [x] what jumps out is that X is more organized than Y, but that is an arbitrary choice we made.  
  - [x] let's make the dots bigger, and gray, and make the line black.
  - [x] consider putting in colorbars
  - [x] put equations in arrows
  - [x] two arrows from col 1, and from col 4
  - [x] maybe put in the other hadamard products, and name them, to connect to fig2 
- fig2: 
  - [x] HHG in legend goes between local ones and global ones
  - [x] the legend in fig2 should link to things in fig1
  - [x] clarify in title: 20 different 1-d dependence structures
  - [x] maybe less lines (eg, try removing mcorr lines?
- [x] fig3: make simpler, use summary stats that our readership can understand.  we can still use this in the appendix. 
- [x] fig4: edit like fig2, but remove dcorr rather than mcorr
- fig5: 
  - [x] title, maybe use 'scales', or "influence of neighborhood size on power"
  - [x] use different colormap from fig1, recall colorbrewer
-  fig6: 
  - [x] shouldn't we compute power for the outlier examples using the other approaches?
  - [x] title: "effect of neighborhood size for different number of outliers'"
  - [x] 2 rows, 3 cols, example for each fraction
  - [x] explicitly denote correlations of interest and outliers in A
  - [x] maybe show example for each different number of outliers?
  - [x] dont call fraction of outliers "p"
  - fig 7
    - [x] increase contrast between 2 lines in A, maybe make one dashed
  - [x] in A, shade everything below 0.05
  - [x] remove D
  - [x] C before B 
  - [x] B: make title more clear. we use both "false discovery rate" and "false positive rate".  make jittered scatter plot.  make y-axis linear. is y-axis "power"?
- fig A1:
  - [x] make dots gray and line black.
- general
  - [x] replace dcorr, mcorr, mantel, etc., with \Dcorr, \Mcorr, \Mantel, etc.  i made macros and replaced some already.

**Comment by cshen6** [comment]
Some questions arises from my plot edits:

**fig1:**
consider putting in colorbars: 
I will put colorbars at bottom, from col 2 onwards? 

put equations in arrows:
 I think putting equations on arrow, will further reduce the room for 5 cols of figures. maybe put on bottom after colobars?

maybe put in the other hadamard products:
 do you mean put in local dVar?

connect to fig2: 
do you mean we give the eventual dCorr number after col 5?

**fig2 & 4:**
 the legend in fig2 should link to things in fig1:
I don't see how to link the legend. What should MGC{mcorr} links to?

maybe less lines:
so you think it is ok to remove mcorr from fig2, and dcorr/mantel from fig4?
but for performance profiles (and whatever replaces them later), we still include all global corr?

**fig5:**
use different colormap from fig1:
if we use different colormaps, what about the heatmaps in fig 6 & 7? Should their color scheme align with fig 5, or fig 1? I thought you wanted to use one style for all?

**fig6:**
2 rows, 3 cols, example for each fraction:
instead of 2rows & 3cols, maybe it is more succinct to show just one percentage (say 0.5) and the corresponding local corr? we can put other twos into the appendix.

explicitly denote correlations of interest and outliers in A:
so I will draw the two mixture components in different color? black and gray?

dont call fraction of outliers "p": 
call it \pi?

**fig 7:**
in A, shade everything below 0.05:
shade the area? or just points below 0.05? 
since it is already black & gray, is there a good example of shading them?

jittered scatter plot:
what do you mean to make the current plot jittered? add small noise to each data point, so they look slightly different?

is y-axis "power"?
no, it is false positive rate, i.e., the percentage of brain region that is falsely identified as significant.

**Comment by jovo** [comment]
skype me?

On Tuesday, June 7, 2016, cshen6 notifications@github.com wrote:

> Some questions arises from my plot edits:
> 
> _fig1:_
> consider putting in colorbars:
> I will put colorbars at bottom, from col 2 onwards?
> 
> put equations in arrows:
> I think putting equations on arrow, will further reduce the room for 5
> cols of figures. maybe put on bottom after colobars?
> 
> maybe put in the other hadamard products:
> do you mean put in local dVar?
> 
> connect to fig2:
> do you mean we give the eventual dCorr number after col 5?
> 
> _fig2 & 4:_
> the legend in fig2 should link to things in fig1:
> I don't see how to link the legend. What should MGC{mcorr} links to?
> 
> maybe less lines:
> so you think it is ok to remove mcorr from fig2, and dcorr/mantel from
> fig4?
> but for performance profiles (and whatever replaces them later), we still
> include all global corr?
> 
> _fig5:_
> use different colormap from fig1:
> if we use different colormaps, what about the heatmaps in fig 6 & 7?
> Should their color scheme align with fig 5, or fig 1? I thought you wanted
> to use one style for all?
> 
> _fig6:_
> 2 rows, 3 cols, example for each fraction:
> instead of 2rows & 3cols, maybe it is more succinct to show just one
> percentage (say 0.5) and the corresponding local corr? we can put other
> twos into the appendix.
> 
> explicitly denote correlations of interest and outliers in A:
> so I will draw the two mixture components in different color? black and
> gray?
> 
> dont call fraction of outliers "p":
> call it \pi?
> 
> _fig 7:_
> in A, shade everything below 0.05:
> shade the area? or just points below 0.05?
> since it is already black & gray, is there a good example of shading them?
> 
> jittered scatter plot:
> what do you mean to make the current plot jittered? add small noise to
> each data point, so they look slightly different?
> 
> is y-axis "power"?
> no, it is false positive rate, i.e., the percentage of brain region that
> is falsely identified as significant.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/RankdCorr/issues/50#issuecomment-224270720, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcq5Na-Y9-Uh5Au5PzfP-IXSxllcPks5qJWl0gaJpZM4IvRe1
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
> _fig1:_
> 
> > consider putting in colorbars:
> > I will put colorbars at bottom, from col 2 onwards?
> > 
> > ok.
> > or just label the colorbar with "max" and "min" so people know that.
> 
> put equations in arrows:
> 
> > I think putting equations on arrow, will further reduce the room for 5
> > cols of figures. maybe put on bottom after colobars?
> 
> arrows between each column, to indicate the direction of motion.
> 
> maybe put in the other hadamard products:
> 
> > do you mean put in local dVar?
> 
> i mean the mantel matrix and the dcorr matrix.
> 
> connect to fig2:
> 
> > do you mean we give the eventual dCorr number after col 5?
> 
> just by naming mantal, dcorr, and mgc{dcorr}, and then fig 1 and fig 2 have
> the same names.
> 
> _fig2 & 4:_
> 
> > the legend in fig2 should link to things in fig1:
> > I don't see how to link the legend. What should MGC{mcorr} links to?
> 
> just by a consistent naming convenion.
> 
> maybe less lines:
> 
> > so you think it is ok to remove mcorr from fig2, and dcorr/mantel from
> > fig4?
> > 
> > yes.
> 
> but for performance profiles (and whatever replaces them later), we still
> 
> > include all global corr?
> 
> unclear.  to be determined.
> 
> _fig5:_
> 
> > use different colormap from fig1:
> > if we use different colormaps, what about the heatmaps in fig 6 & 7?
> > Should their color scheme align with fig 5, or fig 1? I thought you wanted
> > to use one style for all?
> > 
> > yah, sorry.  one color map for all power heatmaps.
> > a different one for distance matrices.
> > does that make sense?
> 
> _fig6:_
> 
> > 2 rows, 3 cols, example for each fraction:
> > instead of 2rows & 3cols, maybe it is more succinct to show just one
> > percentage (say 0.5) and the corresponding local corr? we can put other
> > twos into the appendix.
> > 
> > but showing only one doesn't show the pattern that emerges, right?
> 
> explicitly denote correlations of interest and outliers in A:
> 
> > so I will draw the two mixture components in different color? black and
> > gray?
> > 
> > that's a good idea.
> > i also meant actually write the words "dependent" and "independent" inside
> > the plot.
> 
> dont call fraction of outliers "p":
> 
> > call it \pi?
> > 
> > i think that will confuse the scientists.
> > let's stick with latin.
> > maybe 'w'?
> 
> _fig 7:_
> 
> > in A, shade everything below 0.05:
> > shade the area? or just points below 0.05?
> > since it is already black & gray, is there a good example of shading them?
> > 
> > a lighter gray perhaps?
> > see my last figure of LOL
> > (note that i don't have a gray background in that)
> 
> jittered scatter plot:
> 
> > what do you mean to make the current plot jittered? add small noise to
> > each data point, so they look slightly different?
> > 
> > no, i mean just plot all the FDRs in a single column, but add a small
> > noise to each.
> > the sequence is not important, the only important thing is that they center
> > around 0.05
> 
> is y-axis "power"?
> 
> > no, it is false positive rate, i.e., the percentage of brain region that
> > is falsely identified as significant.
> > 
> > ok, but the title is "false discovery rate", so let's just use one term,
> > ie, re-title it to only provide context.

i guess skype not necessary :)

> —
> 
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/jovo/RankdCorr/issues/50#issuecomment-224270720, or mute
> > the thread
> > https://github.com/notifications/unsubscribe/AACjcq5Na-Y9-Uh5Au5PzfP-IXSxllcPks5qJWl0gaJpZM4IvRe1
> > .
> 
> ## 
> 
> the glass is all full:  half water, half air.
> neurodata.io, jovo calendar
> https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
@cshen6 i think HHG should never be black, it is too eye catching.  let's make it gray?

**Comment by cshen6** [comment]
ok all done. some opinions:

fig1: I didn't put equations there, as the figures look too small if we put equations on all arrows...instead I changed the y label of each figure, for \tilde{A}, A, A^{k^{*}}, etc. Coupling with the caption, I think it should be clear enough?

also note fig1 A,B,C are in fact very similar; so I think it suffices to show one only.

fig3: you can look at the trial figure after fig3 and decide which one you like better.

fig5: I didn't change the color scheme for power heatmap; I changed fig 1 distance heatmap instead.

**Comment by jovo** [comment]
> fig1: I didn't put equations there, as the figures look too small if we
> put equations on all arrows...instead I changed the y label of each figure,
> for \tilde{A}, A, A^{k^{*}}, etc. Coupling with the caption, I think it
> should be clear enough?
1. [ ] so, one important point that we are not yet conveying is that all
   that is required, in addition to the data, is a metric. so, i still want
   that on the first pair of arrows. eg, i want d(x_i, x_j) on the top one,
   and d(y_i,y_j) on the bottom one.
2. [ ] i also want the words, "Mantel", "Dcorr", and "MGC_D^{kl}" in there.
   so, maybe we can make the existing titles 2 lines, and add those words on
   the second line?

> also note fig1 A,B,C are in fact very similar; so I think it suffices to
> show one only.
- [ ] yes, i don't understand why there are 3?
  what i was hoping for is 4 columns,
  with col 2-4 each having 3 rows

A, B, and A.B

does that make sense?

also, can we use a different function, like the spiral for example?
i want the local versions of both A & B to be sparse.
so, choose a really good but relatively small value for both k & l?
- [ ] for the outlier fig, can you make the letters closer to the panels?
  also, i want the titles to say "30% Outliers", so the reader does not have
  to remember what 'w' means.
  
  otherwise, i think perfect.

fig3: you can look at the trial figure after fig3 and decide which one you

> like better.
> 
> fig5: I didn't change the color scheme for power heatmap; I changed fig 1
> distance heatmap instead.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/RankdCorr/issues/50#issuecomment-224786264, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcpWTb20huZFUNb8J3R74PFh6ZoVTks5qJ3wogaJpZM4IvRe1
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
- [x] for the last figure
  - [x] A; fonts are too small. 
  - [x] change titles to: "Brain Shape vs. Disorder", "Brain Graph vs. Creativity", and "Brain Activity vs. Fake Movie"
  - [x] also, i don't love the significant bar.  let's make all values below 0.05 black, and the ones above gray, and we'll use the two different line style to differentiate
  - [x] for C, let's plot the kernel density estimate, and put little ticks marks at the bottom to indicate the actual data, know what i mean?

**Comment by cshen6** [comment]
figure 7 edited and uploaded, let me know what should be further changed there.

**Comment by jovo** [comment]
definitely better.

can you make the non-solid line just a regular dashed line?
the the values < 0.05, can you make the line thicker?
it doesn't pop out as much as i want it to.

thanks, j

On Thu, Jun 9, 2016 at 10:19 PM, cshen6 notifications@github.com wrote:

> figure 7 edited and uploaded, let me know what should be further changed
> there.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/RankdCorr/issues/50#issuecomment-225013852, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjctQdsqyBtUG0YDXFeapR8kaIRLX4ks5qKHU4gaJpZM4IvRe1
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
ok, you can check the last figure out again.

note that rather than set all <0.05 scales black, I only plot consecutive significant scales black.

**Comment by cshen6** [comment]
the outlier titles are also updated.
not sure how to deal with the letter position though...I will open a separate issue on this, to be solved later.

**Comment by jovo** [comment]
- fig 4: it looks way better!
  - [ ] i think i'd only have a y-axis label on the far left,
    in fact, i don't even think i'd have the vertical line for the other plots,
    it will be implied.
  - [ ] i would try adding a thicker mean line
- fig outliers:
  - [ ] why did the correlation go back up? shouldn't it be only 0.9, it
    looks close to one.  otherwise, is great.

On Fri, Jun 10, 2016 at 12:37 AM, cshen6 notifications@github.com wrote:

> ok, you can check it out again.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/RankdCorr/issues/50#issuecomment-225047601, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjchMTtlQKY5s5GZLHLF9bEs0XSODBks5qKJWqgaJpZM4IvRe1
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
- fig 4: 
  I added a thicker mean line, but visually the other lines have to use a different line style for the mean line to be obvious. 

I also added the HHG straight line into the left most figure, what do you think?
- fig outliers:
  so it should be 70% outlier, 50% outlier, 30% outlier...corresponding to w=0.3, 0.5, 0.7 respectively.

**Comment by jovo** [comment]
- [ ] re:thicker mean, maybe make it even thicker?
- [ ] re:gray HHG line, i don't love it.  what do you think? did you try
  making a 4th panel with just dots?
- [ ] re:y-axis labels, let's just put 0 & 1, no intermediate values,
- [ ] re:outlier fig: looks great now! just need to fix those pesky
  subfigure letters.  we can honestly just remove them if its easier.

On Fri, Jun 10, 2016 at 3:31 AM, cshen6 notifications@github.com wrote:

> - fig 4: I added a thicker mean line, but visually the other lines
>   have to use a different line style for the mean line to be obvious.
> 
> I also added the HHG straight line into the left most figure, what do you
> think?
> - fig outliers: so it should be 70% outlier, 50% outlier, 30%
>   outlier...corresponding to w=0.3, 0.5, 0.7 respectively.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/RankdCorr/issues/50#issuecomment-225072749, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcgVz7uAJeLswppBF1jEU9bxaSKVsks5qKL6GgaJpZM4IvRe1
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
I would like to ask about figure 1 here, there is something I don't understand no matter how long I stare at the sentences :-)

**1. [ ] so, one important point that we are not yet conveying is that all
that is required, in addition to the data, is a metric. so, i still want
that on the first pair of arrows. eg, i want d(x_i, x_j) on the top one,
and d(y_i,y_j) on the bottom one.**
ok, adding a short equation on one arrow is still fine.

**\- [ ] yes, i don't understand why there are 3?
what i was hoping for is 4 columns,
with col 2-4 each having 3 rows
A, B, and A.B
does that make sense?**
For figure 1:
col 1 is scatter plot, 
col 2 is distance matrices \tilde{A} and \tilde{B},
col 3 is centered distance A and B,
col 4 is truncated distances A^{k} and B^{l},
col 5 is the entry-wise product of A^{k}B^{l}, whose sum yields local covariance.
So col2-4 already have 2 rows, to illustrate A and B. But the entri-wise product of col2 and 3 are never
used for local correlation computation. So A.B makes sense only for col3 and col4, for showing the global and local covariance respectively.

But if we are to fit in Mantel/Dcorr/Mcorr by three rows, then among col 2-4, we can only take one column(I guess col4), and show it for three methods. 
Still, as you see in previous figure 1(A)(B)(C), the three methods are almost the same in all heatmaps (except the diagonal entries)! 
So, my opinion is that showing all three methods by flowchat won't provide more insight/information, but merely a repetition. Instead, we should use one of the three methods for figure 1, then say in text or caption that the other two shares the same procedure and very similar heatmap. What do you think?

**also, can we use a different function, like the spiral for example?
i want the local versions of both A & B to be sparse.
so, choose a really good but relatively small value for both k & l?**
Spiral doesn't look good (I can show you if you want), because the neighborhood of A is very small so A^{k} will be very sparse and concentrated almost only on diagonals.
But I can switch to type 8 two parabolas, which does make both A^{k} and B^{l} sparse.
Still, parabola is the simplest non-linear function, and matches up with the theorem where we use quadratic for illustration; and I actually like one being sparse while the other isn't, since the power heatmaps actually imply this phenomenon for many nonlinear types.
I can send you the plots in email for you to decide though.

**Comment by jovo** [comment]
> So, my opinion is that showing all three methods by flowchat won't provide
> more insight/information, but merely a repetition. Instead, we should use
> one of the three methods for figure 1, then say in text or caption that the
> other two shares the same procedure and very similar heatmap. What do you
> think?

i vote we look.
it is an important figure, there is no need for us to guess.
we'll make both and look and ask others for feedback.

> _also, can we use a different function, like the spiral for example? i
> want the local versions of both A & B to be sparse. so, choose a really
> good but relatively small value for both k & l?_
> Spiral doesn't look good (I can show you if you want), because the
> neighborhood of A is very small so A^{k} will be very sparse and
> concentrated almost only on diagonals.
> But I can switch to type 8 two parabolas, which does make both A^{k} and
> B^{l} sparse.
> Still, parabola is the simplest non-linear function, and matches up with
> the theorem where we use quadratic for illustration; and I actually like
> one being sparse while the other isn't, since the power heatmaps actually
> imply this phenomenon for many nonlinear types.
> I can send you the plots in email for you to decide though.

please do send them.
i agree, parobola is wonderfully simple.
but the thing that pops out is the difference between A & B, and that is
not what we want to be the most salient feature.

note, we need not take k\* and l*, it is just an illustration...

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/RankdCorr/issues/50#issuecomment-225406974, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcg3wRhNBeMeykpn33djPqaGtUnhAks5qK3aAgaJpZM4IvRe1
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
If we look at figA/B/C attached, you can see fig A (dcorr flowchart) almost
coincides with fig B (mcorr flowchart) in every column, except the
diagonals are different.

Then from fig B to fig C, although the exact magnitudes for matrix B and
B^{l} are different, otherwise the figures are very similar too.

Then in the following, you can see col 4&5 for type 8, and col 4&5 for type
13. (col1-3 are pretty standard and similar for all types).

For col4A and B, both type 8 and 13 are sparse for both matrices. But type
13 is kind of too sparse, I think.

On Sun, Jun 12, 2016 at 5:25 AM, joshua vogelstein <notifications@github.com

**Comment by cshen6** [comment]
can you skype? let's discuss and finalize...

On Sun, Jun 12, 2016 at 3:20 PM, Cencheng Shen cshen6@jhu.edu wrote:

> If we look at figA/B/C attached, you can see fig A (dcorr flowchart)
> almost coincides with fig B (mcorr flowchart) in every column, except the
> diagonals are different.
> 
> Then from fig B to fig C, although the exact magnitudes for matrix B and
> B^{l} are different, otherwise the figures are very similar too.
> 
> Then in the following, you can see col 4&5 for type 8, and col 4&5 for
> type 13. (col1-3 are pretty standard and similar for all types).
> 
> For col4A and B, both type 8 and 13 are sparse for both matrices. But type
> 13 is kind of too sparse, I think.
> 
> On Sun, Jun 12, 2016 at 5:25 AM, joshua vogelstein <
> notifications@github.com> wrote:
> 
> > > So, my opinion is that showing all three methods by flowchat won't
> > > provide
> > > more insight/information, but merely a repetition. Instead, we should
> > > use
> > > one of the three methods for figure 1, then say in text or caption that
> > > the
> > > other two shares the same procedure and very similar heatmap. What do
> > > you
> > > think?
> > 
> > i vote we look.
> > it is an important figure, there is no need for us to guess.
> > we'll make both and look and ask others for feedback.
> > 
> > > _also, can we use a different function, like the spiral for example? i
> > > want the local versions of both A & B to be sparse. so, choose a really
> > > good but relatively small value for both k & l?_
> > > Spiral doesn't look good (I can show you if you want), because the
> > > neighborhood of A is very small so A^{k} will be very sparse and
> > > concentrated almost only on diagonals.
> > > But I can switch to type 8 two parabolas, which does make both A^{k} and
> > > B^{l} sparse.
> > > Still, parabola is the simplest non-linear function, and matches up with
> > > the theorem where we use quadratic for illustration; and I actually like
> > > one being sparse while the other isn't, since the power heatmaps
> > > actually
> > > imply this phenomenon for many nonlinear types.
> > > I can send you the plots in email for you to decide though.
> > 
> > please do send them.
> > i agree, parobola is wonderfully simple.
> > but the thing that pops out is the difference between A & B, and that is
> > not what we want to be the most salient feature.
> > 
> > note, we need not take k\* and l*, it is just an illustration...
> > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/jovo/RankdCorr/issues/50#issuecomment-225406974,
> > > or mute
> > > the thread
> > > <
> > > https://github.com/notifications/unsubscribe/AACjcg3wRhNBeMeykpn33djPqaGtUnhAks5qK3aAgaJpZM4IvRe1
> > > 
> > > .
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > neurodata.io, jovo calendar
> > <
> > https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
> > 
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/jovo/RankdCorr/issues/50#issuecomment-225422099, or mute
> > the thread
> > https://github.com/notifications/unsubscribe/ALX0y7IFd2ZLhWsyAEntYmgjv6yslxZjks5qK9ChgaJpZM4IvRe1
> > .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
