### ISSUE TITLE
computing all p-values?

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#51]
do the critical values change for each neighborhood size? i would think so.  nonetheless, do they change sufficiently little such that we can find regions of test-statistic that are large, rather than regions of p-value that are small? our test of course would still be valid, the question is whether it would work well.

i think this is _not_ something to check prior to submission, just jotting it down here now for completeness.

**Comment by cshen6** [comment]
I agree. 

In particular, this strategy works well for local mcorr, which could motivate a t-test without the need to do permutation test. 

We should delve more into it once the current one is done.

**Comment by cshen6** [comment]
the new valid procedure kind of makes use of all local dcorr directy without going for all local p-values.
