### ISSUE TITLE
what do you think about removing mantel from fig 2?

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#53]
i think we should put the original figures (with all 7 tests) in the appendix,
and in figure 2, only show MGC_D, Dcorr, and HHG.

its only for multiplicative noise that mantel wins, 
and it makes the story (and the figure, imho), less compelling.

thoughts?

**Comment by cshen6** [comment]
Yeah just did it. Looks good enough to me!!=

**Comment by jovo** [comment]
agreed!
