### ISSUE TITLE
categorical?

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#59]
"For the categorical disorder variable,
we use squared Euclidean distance, then add $1$ to every non-diagonal entry (so only the diagonals are of distance $0$)."

is that true? the covariate isn't really categorical, it is discrete i think.
both are fine, i just want to make sure you used a 0-1 loss or not.

**Comment by cshen6** [comment]
The covariate is categorical: 1,2,3 correspond to no disease, early
symptom, and disease, for Major depressive dis-order.

Note that we can use other distance measure:
a direct Euclidean distance without adding 1 is actually fine for both
mcorr and mantel (since they do not use diagonal any way).

Using 0-1 is also ok as I recall, i.e., set d_ij=1 for different label and
0 for same label.

Which one do you prefer?

On Thu, Jun 23, 2016 at 9:24 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
i think 1,2,3 makes the most sense, and then just euclidean.
but what did we do?

**Comment by cshen6** [comment]
we did Euclidean, followed by adding 1 to non-diagonal entries.

But let us just use Euclidean then! I will update it accordingly very
quickly.

On Thu, Jun 23, 2016 at 9:43 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
i think your thing makes sense, is it a metric?

On Thu, Jun 23, 2016 at 10:01 PM, cshen6 notifications@github.com wrote:

> we did Euclidean, followed by adding 1 to non-diagonal entries.
> 
> But let us just use Euclidean then! I will update it accordingly very
> quickly.
> 
> On Thu, Jun 23, 2016 at 9:43 PM, joshua vogelstein <
> notifications@github.com
> 
> > wrote:
> > 
> > i think 1,2,3 makes the most sense, and then just euclidean.
> > but what did we do?
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/jovo/RankdCorr/issues/59#issuecomment-228235233,
> > or mute
> > the thread
> > <
> > https://github.com/notifications/unsubscribe/ALX0y98yfuZ8C2W4G1eqM-unt9pElT9Iks5qOzZRgaJpZM4I9Yq0
> > 
> > .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/RankdCorr/issues/59#issuecomment-228237673, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcrILzF1V4ewtLf4wjqO4t1XV2pReks5qOzqWgaJpZM4I9Yq0
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
yes it is a metric...and it sets zero distance for the same points
only, while the other way sets zero distance for same labels.
Then we keep it the old way?

**Comment by jovo** [comment]
i think keep it.
metric means it satisfies all the properties of a metric?

On Thu, Jun 23, 2016 at 11:22 PM, cshen6 notifications@github.com wrote:

> yes it is a metric...and it sets zero distance for the same points
> only, while the other way sets zero distance for same labels.
> Then we keep it the old way?
> 
> On Thu, Jun 23, 2016 at 10:32 PM, joshua vogelstein <
> notifications@github.com> wrote:
> 
> > i think your thing makes sense, is it a metric?
> > 
> > On Thu, Jun 23, 2016 at 10:01 PM, cshen6 notifications@github.com
> > wrote:
> > 
> > > we did Euclidean, followed by adding 1 to non-diagonal entries.
> > > 
> > > But let us just use Euclidean then! I will update it accordingly very
> > > quickly.
> > > 
> > > On Thu, Jun 23, 2016 at 9:43 PM, joshua vogelstein <
> > > notifications@github.com
> > > 
> > > > wrote:
> > > > 
> > > > i think 1,2,3 makes the most sense, and then just euclidean.
> > > > but what did we do?
> > > > 
> > > > —
> > > > You are receiving this because you were mentioned.
> > > > Reply to this email directly, view it on GitHub
> > > > <https://github.com/jovo/RankdCorr/issues/59#issuecomment-228235233
> > > > ,
> > > > or mute
> > > > the thread
> > > > <
> > 
> > https://github.com/notifications/unsubscribe/ALX0y98yfuZ8C2W4G1eqM-unt9pElT9Iks5qOzZRgaJpZM4I9Yq0
> > 
> > > > .
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/jovo/RankdCorr/issues/59#issuecomment-228237673,
> > > or mute
> > > the thread
> > > <
> > 
> > https://github.com/notifications/unsubscribe/AACjcrILzF1V4ewtLf4wjqO4t1XV2pReks5qOzqWgaJpZM4I9Yq0
> > 
> > > .
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > neurodata.io, jovo calendar
> > <
> > 
> > https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
> > 
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/jovo/RankdCorr/issues/59#issuecomment-228242250,
> > or mute
> > the thread
> > <
> > https://github.com/notifications/unsubscribe/ALX0y_lD_AjT9fFj8pKO-jDqunNetmpXks5qO0GogaJpZM4I9Yq0
> > 
> > .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/RankdCorr/issues/59#issuecomment-228249417, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcmAkfSBn4cW5MY0xxKkppO4VjseGks5qO01qgaJpZM4I9Yq0
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
