### ISSUE TITLE
name

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#60]
MGC:

multiscale graph correlation

multiscale generalized correlation

or something else? what do you think?

**Comment by cshen6** [comment]
what about multiscale correlation (MSC)?

otherwise multiscale generalized correlation sounds better, although "multiscale" and "generalized" is a bit conflicting?

**Comment by jovo** [comment]
well, the acronym obviously has to spell "magic",
so when you are giving your job talk, you can talk about your "magic test"!

On Fri, Jun 24, 2016 at 9:26 AM, cshen6 notifications@github.com wrote:

> what about multiscale correlation (MSC)?
> 
> otherwise multiscale generalized correlation sounds better, although
> "multiscale" and "generalized" is a bit conflicting?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/MGC/issues/60#issuecomment-228344772, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjci98Il5EMyvPkD3zPinay-mq-HJYks5qO9sCgaJpZM4I9vYN
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
Then let us do multiscale generalized correlation? I will change it on tex, when I finish other plots issues

**Comment by jovo** [comment]
great!

On Fri, Jun 24, 2016 at 9:50 AM, cshen6 notifications@github.com wrote:

> Then let us do multiscale generalized correlation? I will change it on
> tex, when I finish other plots issues
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/MGC/issues/60#issuecomment-228350825, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcqZlpMFrjIKJUAvFkHT68jljUaWiks5qO-C7gaJpZM4I9vYN
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
all replaced, you will see in next push
