### ISSUE TITLE
Minors

### ISSUE THREAD

**Issue by cshen6** [neurodata/MGC-paper#61]
- [x] figure 1 and caption
- [x] hd figure spiral, 
- [x] type 18 permutation needs to be re-done
- [x] figure 2 starts at 1d for each panel
- [x] legend and plot, always order Mcorr first
- [x] fig 5c can only see 15 points, but there are 26, maybe add some jitter in y-axis to those points?
- [x] fix references (eg, "available at" is not a journal name, neither is the arXiv id, the Gorfine ref is weird, Zheng is werid, some Szekely references are repeated maybe?
- [x] there is no such thing in our paper as "d_y", so why do we call the other "d_x"? how about "D", and we still let "d" be the dummy indicator variable? alternately, we could use "p" instead of "d_x" or "D". what do you think?
- [x] superscript 'd' is a fine way to denote which element of a vector, however, you also use it to denote power (in eq 13), which is a bit confusing.  maybe use x[d] instead of x^d throughout? what do you think?
- [x] setting 14 & 16, why is the normal distribution for epsilon set to the power d_x?
- [ ]

**Comment by cshen6** [comment]
yeah, x[d] should be good.

d_x is the dimension for x, d_y is the dimension for y, so they are still necessary (though they appear very infrequently in paper) ? p is reserved for p-value.

**Comment by cshen6** [comment]
for reference: I thought Da's paper reference is fine (showing arXiv only)?
I fixed various arXiv references now, which was showing url previously; also Gorfine ref is now showing as technical report, which is on their own website but not arxiv.
Also fixed last reference, since Fosdick paper is now out on JASA.
There are no repetition in Gabor's refs, it is just we cite too many of them and some of them are from same journal :-)

**Comment by jovo** [comment]
there are a bunch of places in the text that i put a \cs{} comment for you.
i think once you fix them, we'll be done v1 to send brett!

On Sat, Jun 25, 2016 at 5:39 PM, cshen6 notifications@github.com wrote:

> for reference: I thought Da's paper reference is fine (showing arXiv only)?
> I fixed various arXiv references now, which was showing url previously;
> also Gorfine ref is now showing as technical report, which is on their own
> website but not arxiv.
> Also fixed last reference, since Fosdick paper is now out on JASA.
> There are no repetition in Gabor's refs, it is just we cite too many of
> them and some of them are from same journal :-)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/MGC/issues/61#issuecomment-228571751, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjckuzgb7GH45Jw6Ngf4FAyanAVqNCks5qPaAQgaJpZM4I-PxB
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
