### ISSUE TITLE
final revisions prior to sending to brett

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#63]
- [x] a bunch of \cs{} comments in text, please fix
- [x] f:1DAll is missing sample size for x-axis
- [x] fig A4 has x & y axis labeled for all plots, make the same as the one in the main paper
- [x] superscript for dimension is a convention i can't get behind, but it is still present and confusing.  i recommend x[d].  
- [x] bracket convention.  i would reserve { } for sets, and [ ] for dimension, and use ( ) for functions and grouping, and if there is a possibility of ambiguity, but a \times there.  eg, b(x+y) is ambigious, is 'x+y' the operand, or is it b \times (x + y).  never leave room for doubt. note that we sometimes use ( ) for sets, eg (a_{ij}), etc. even if we don't explicitly state our conventions, we should have them and use them.
- [x] we never use d_y in the main paper, only the appendix.  that's why i was suggestion we use D (and then maybe D_y), because we write _d_x_ over 90 times, and d_y on like 10. and d_x is ugly, i think. what do you think?
- [x] what do you think about the following idea: in Fig 1, you show that green is good, and purple is bad (essentially) from the A.*B matrices.  what if we made that the color scheme throughout, so
  -  MGC is always green, we can use solid, dashed, and dotted for M, D, and A, respectively
  - global variants are always magenta, using same color line style them.
  - since color is more salient than line style, the visual difference between _us_ & _them_ will be more stark.  thoughts?

**Comment by cshen6** [comment]
Just updated some change.
All \cs comments are replied by \jv. Only thing I am not sure is for real data second experiment.

There is a missing ref \Hou2016, I think you must mean \Huo 2016 the fast dcov paper, so I changed it.

When I compile the tex, there is also a warning saying \sc is not supported in math mode. Not sure if it is your intention or not, but I changed the command so it is compatible with math mode, and every \Mgc, \Mcorr have the same font in paper and math environment.

I agree with all your comments on superscript, brackets, and D. I can make those changes, if you are not making any other change?

And will settle other plot issues after lunch :-)

**Comment by jovo** [comment]
great

**Comment by cshen6** [comment]
Figure A4 has all sample sizes for x and y, because each panel has different sample size.

But figure 4 is for hd panels, where all sample sizes are the same. So it suffices to label the x and y axis for one panel.

**Comment by jovo** [comment]
skype real quick?

On Sun, Jun 26, 2016 at 3:23 PM, cshen6 notifications@github.com wrote:

> Figure A4 has all sample sizes for x and y, because each panel has
> different sample size.
> 
> But figure 4 is for hd panels, where all sample sizes are the same. So it
> suffices to label the x and y axis for one panel.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/MGC/issues/63#issuecomment-228617649, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjctYM2n7Rid2qa8_XEdEMy7ThaER1ks5qPtGrgaJpZM4I-kNz
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
just updated all issues. Remaining figure 1 issue will be solved in the next figure issue.
