### ISSUE TITLE
C vs c

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#67]
shouldn't C = A .\* B, 
and c = sum(c)

?

if we do define C as above, then we can modify fig 1 to write C and Ctilde

and then, on the x-axis of the test statistic distribution fig, we could write:

c = 0.03 & c^kl = 0.31

?

i'm also concerned about '.*'.
will people know what that means?
perhaps:

> c_ij = a_ij \* b_ij

will be more clear?

or C = A \circ B

wiki notation for hadamard product is \circ...

thoughts?

note: we only explicitly define and discuss the matrix A o B in Fig 1, which is kind of interesting, 
since it really is the object of interest....

**Comment by cshen6** [comment]
ok, good points! Essentially all C's will become c, and we define an
additional C for figure 1 only.

On Sun, Jun 26, 2016 at 7:13 PM, joshua vogelstein <notifications@github.com

**Comment by cshen6** [comment]
yes C is an object of interest. But it seems we don't need C after all?
Just A \circ B will suffice?

**Comment by jovo** [comment]
agreed

On Sun, Jun 26, 2016 at 8:32 PM, cshen6 notifications@github.com wrote:

> yes C is an object of interest. But it seems we don't need C after all?
> Just A \circ B will suffice?
> 
> On Sun, Jun 26, 2016 at 8:27 PM, Cencheng Shen cshen6@jhu.edu wrote:
> 
> > ok, good points! Essentially all C's will become c, and we define an
> > additional C for figure 1 only.
> > 
> > On Sun, Jun 26, 2016 at 7:13 PM, joshua vogelstein <
> > notifications@github.com> wrote:
> > 
> > > Assigned #67 https://github.com/jovo/MGC/issues/67 to @cshen6
> > > https://github.com/cshen6.
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/jovo/MGC/issues/67#event-704356908, or mute the
> > > thread
> > > <
> > > https://github.com/notifications/unsubscribe/ALX0y0chx03B1CTB2Hnp7ZqksUbQXMXkks5qPweDgaJpZM4I-qsa
> > > 
> > > .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/MGC/issues/67#issuecomment-228632915, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcgAmyp8jjQMJspQNKG-NunS7Smt_ks5qPxofgaJpZM4I-qsa
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
so, you want to use \circ instead of '.*' it seems.  
fine with me.
