### ISSUE TITLE
caxis...NO!!!

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#70]
ugh, i noticed you use caxis all over the place.
it is very misleading, because it truncates, but then you never actually say that you did that, 
that is bad!

also, for p-value maps/plots, i find it almost always more beneficial to plot log(pvalue), rather than pvalue.

can you remove all the caxis, and change things to logscale as appropriate?
i changed it in figure 1.

**Comment by cshen6** [comment]
yeah I like log scales too! Will change them all.

For c-axis of p-value map, they do truncate and I will change them...

But the c-axis for A, \tilde{A}, etc, does not truncate: for example, the un-truncated caxis could be [-3,5], then I use c-axis to set [-5,5] instead, so the middle point corresponds to white. So we should still use those c-axis...

**Comment by cshen6** [comment]
updated. The only other p-value heatmap is in real data section, which looks much better in log scale!

**Comment by jovo** [comment]
yah, i'm the only one who apparently knows that pvalues should be looked at
on a log scale (typically).

On Wed, Jun 29, 2016 at 10:20 AM, cshen6 notifications@github.com wrote:

> updated. The only other p-value heatmap is in real data section, which
> looks much better in log scale!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/MGC/issues/70#issuecomment-229370824, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcvfdC4mTuJInRs1-Z-ai2PwsyByGks5qQn9DgaJpZM4JAvFT
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
