### ISSUE TITLE
power vs pvalue maps

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#72]
i think the following would be worthwhile:

for the 20 simulations, also generate pvalue maps (on log scale, no caxis).
i want to look at them, 
and maybe even compute the correlation between log(pvalue) and power.
or see whether i can look at the data more, play with thresholding, and find a good/better way.
i don't think something to do before submission, but definitely something i want to do.

**Comment by cshen6** [comment]
updated this function in code/temp folder, called
plot_simulation_pValueAndPower.m

You can specify the type, sample size n, and the dimensionality, then
observe the p-value map and power map.

Note that the power map is based on pre-calculated data, while the p-value
is always re-calculated in code by 1000 permutations (so it is different
every time).

On Wed, Jun 29, 2016 at 8:07 AM, joshua vogelstein <notifications@github.com
