### ISSUE TITLE
Rank MGC

### ISSUE THREAD

**Issue by cshen6** [neurodata/MGC-paper#73]
We should re-visit this too, post-submission.

Now we understand much better than 1 year ago, we can do a better rank MGC now.
I tried briefly, some interesting findings:
1. With a few tweaks, rank MGC is almost equivalent throughout dcorr / mcorr / MGC, theoretically and numerically. So it can be a single framework.
2. In existing simulations, rank MGC is equivalent to MGC_{m} for almost all simulations, including its h-d advantages. 
3. For real data, rank MGC can now detect significant p-value for Brain CxP.

So we should work on this post-submission too, and include it in the grant application.

**Comment by jovo** [comment]
agreed.
also, MGC detects significant p-value for Brain CxP, but you have to use my
"p = min t s.t. a cc w/|cc|>3 exists" strategy

On Sun, Jul 3, 2016 at 11:36 AM, cshen6 notifications@github.com wrote:

> We should re-visit this too, post-submission.
> 
> Now we understand much better than 1 year ago, we can do a better rank MGC
> now.
> I tried briefly, some interesting findings:
> 1. With a few tweaks, rank MGC is almost equivalent throughout dcorr /
> mcorr / MGC, theoretically and numerically. So it can be a single framework.
> 2. In existing simulations, rank MGC is equivalent to MGC_{m} for almost
> all simulations, including its h-d advantages.
> 3. For real data, rank MGC can now detect significant p-value for Brain
> CxP.
> 
> So we should work on this post-submission too, and include it in the grant
> application.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/MGC/issues/73, or mute the thread
> https://github.com/notifications/unsubscribe/AACjcqkiUNhPHgQV8Y1TTeo7TFVQpx9dks5qR9b1gaJpZM4JD5DA
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
I will move this issue to the other repo
