### ISSUE TITLE
brett feedback

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#76]
for spiral, consider a few different pairs of points, and walk through each column of figure to see if we can build intuition that way.

**Comment by jovo** [comment]
ok, i did this, and i updated plot_auxiliary to do everything (other than arrows, which we can discuss).
i generated all 20 plots and looked at them, they are quite illustrative.

i wonder about adding the Mantel A.*B and p-value plot now?

one thing that would be really helpful (brett & i now think) is a table beneath the figure showing, for 4 points:

A(2,3)
B(2,3)
C(2,3)

A(1,4)
B(1,4)
C(1,4)

C(2,3)+C(1,4)

for each of Mantel, Mcorr, and MGC

having chosen the points to illustrate that Mantel/Mcorr do poorly when MGC does well?

**Comment by jovo** [comment]
added in commit 14bee609472bd5882edd761876b50bbe37e989e6

**Comment by jovo** [comment]
i made a few more changes, but i couldn't figure out how to get the colorbar back in there without changing the size of a panel.
can you put it in the bottom left panel? or middle left? which ever looks better?

**Comment by cshen6** [comment]
colorbar added back in bottom left panel, and adjust all minor problems we went through. Only problem is the current figA is kind of squeezed when shown on my screen...
