### ISSUE TITLE
p-value vs power maps

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#78]
https://www.dropbox.com/sh/v2qdjnof5niya9z/AACgf1J4DyasgaX49r6lSlOZa?dl=0

look for files called "PowerEst_type1_n100_d1.pdf"

the maps look strikingly similar, imho.

note that plot_simulation_pValueAndPower(19,100,1) does not work.

can you add another row, which is a binary map of the optimal scales, 
using either our estimate based on p-value or power, as appropriate?

**Comment by cshen6** [comment]
updated optimal scales, and fixed type 19

**Comment by jovo** [comment]
you were going to add noise to type 19, right?
did that happen?
is there an issue for it?

On Mon, Jul 11, 2016 at 10:13 AM, cshen6 notifications@github.com wrote:

> updated optimal scales, and fixed type 19
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/MGC/issues/78#issuecomment-231746532, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjchvnocQySVY7qGWLse1gH9RMS7oaks5qUk-OgaJpZM4JIJdT
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
no, l will add it to next step.

On Mon, Jul 11, 2016 at 2:57 PM, joshua vogelstein <notifications@github.com

> wrote:
> 
> you were going to add noise to type 19, right?
> did that happen?
> is there an issue for it?
>
