### ISSUE TITLE
update theorem statements

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#80]
maybe add 'n', oracle, sample, etc.

**Comment by jovo** [comment]
i did this in the main text.

if you agree, perhaps propagate to the appendix and close?

**Comment by cshen6** [comment]
ok  let me check it out.

If you mean the theorem statements,  they are already (and are still)
aligned with the appendix thms when I sync yesterday.

**Comment by cshen6** [comment]
I checked again, and made sure appendix thms statement and proofs are now ok and consistent with main text.
