### ISSUE TITLE
fig 1 arrows and text and order

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#85]
1. what happened to the arrows and text that we used to have in fig 1?
- compute distances
- double center
- rank truncate

?
1. also, i think we should switch p-value map and power maps.  what do you think?

**Comment by cshen6** [comment]
the arrows were never in the code?

the text is added back (I commented out to save space previously);
so you should see it once you generate figA again.

On Thu, Aug 11, 2016 at 2:23 PM, joshua vogelstein <notifications@github.com

**Comment by cshen6** [comment]
I am ok either way, on how to put p-value map and power maps, it is just one line position change in plot_schematic.m for them.

When I switch them, the x label of the power map goes mixed with the title of p-value map on my machine...so I am not sure which one is aesthetically more pleasing. Your call?
