### ISSUE TITLE
do we care about this

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#94]
http://projecteuclid.org/euclid.aoas/1469199886

i couldn't download it for some reason

**Comment by cshen6** [comment]
nope, cannot get it there...I also asked Youjin and no success.

If you really want to see it I will email the author?

On Mon, Aug 22, 2016 at 9:29 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
[AOAS1601-012RA0.pdf](https://github.com/jovo/MGC/files/432477/AOAS1601-012RA0.pdf)

found it.  the senior author wrote about quantifying dependency (we cite it), 
so i wanted to see if it is relevant for mgc, but doesn't seem particularly relevant.
