### ISSUE TITLE
heller 2016

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#98]
we don't cite this: http://www.jmlr.org/papers/volume17/14-441/14-441.pdf

but, "An Empirical Study of Leading Measures of Dependence" says that it is better than the original HHG result.  opine?

i presume we used the earlier HHG approach, that only had a two-by-two table, not the newer one?

**Comment by cshen6** [comment]
no we don't.

because it is for univariate! 

plus it is not always better than original HHG, like in table 2

**Comment by jovo** [comment]
i cited it.
